const datos = [
    { etiqueta: "AUTO", imagen: "img/auto.png" },
    { etiqueta: "STATION_WAGON", imagen: "img/station_wagon.png" },
    { etiqueta: "PICK_UP", imagen: "img/pick_up.png" },
    { etiqueta: "PANEL", imagen: "img/panel.png" },
    { etiqueta: "RURAL_COMBI", imagen: "img/rural_combi.png" },
    { etiqueta: "MICRO", imagen: "img/micro.png" },
    { etiqueta: "BUS_2E", imagen: "img/bus_2e.png" },
    { etiqueta: "BUS_3E", imagen: "img/bus_3e.png" },
    { etiqueta: "CAMION_2E", imagen: "img/camion_2e.png" },
    { etiqueta: "CAMION_3E", imagen: "img/camion_3e.png" },
    { etiqueta: "CAMION_4E", imagen: "img/camion_4e.png" },
    { etiqueta: "ST:2S1/2S2", imagen: "img/2s12s2.png" },
    { etiqueta: "ST:2S3", imagen: "img/2s3.png" },
    { etiqueta: "ST:3S1/3S2", imagen: "img/3s13s2.png" },
    { etiqueta: "ST:3S3", imagen: "img/3s3.png" },
    { etiqueta: "T:2T2", imagen: "img/2t2.png" },
    { etiqueta: "T:2T3", imagen: "img/2t3.png" },
    { etiqueta: "T:3T2", imagen: "img/3t2.png" },
    { etiqueta: "T:3T3", imagen: "img/3t3.png" }
  ];
